# -*- coding: utf-8 -*-
"""Password Generator .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WJwa0rXh67g4WyU3SP4ShaKg1qdhvPQ5
"""

import numpy as np
!pip install ivy
!pip install pywhatkit



import random
pass1=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','1','2','3','4','5' ,'6','7','8','9','0','!']

password=""

for x in range (8):
   password = password + random.choices(pass1)[0]

print('your new password is:\n',password)